  cluster:
    bastionHost: ${bastion_host_enabled}
    controlPlaneInstanceType: ${control_plane_instance_type} 
    controlPlaneReplicas: ${control_plane_instance_replicas}  
    ingressInstanceType: ${ingress_instance_type}
    ingressReplicas: ${ingress_replicas}
    kubernetesVersion: ${kubernetes_version}
    name: ${cluster_name}
    podCidrBlock: ${pod_cidr_block} 
    region: ${region}
    sshKeyName: ${ssh_key_name} 
    workerInstanceType: ${worker_instance_type}
    workerReplicas: ${worker_replicas}
  network:
    vpc:
      cidrBlock: ${vpc_cidr_block}
