apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }} 
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.cluster.podCidrBlock }} #  192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: KubeadmControlPlane
    name: {{ .Values.cluster.name }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: AWSCluster
    name: {{ .Values.cluster.name }} 
