apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: "{{ .Values.cluster.name }}-worker"
spec:
  template:
    spec:
      iamInstanceProfile: nodes.cluster-api-provider-aws.sigs.k8s.io
      instanceType:  {{ .Values.cluster.workerInstanceType }}
      sshKeyName:  {{ .Values.cluster.sshKeyName }}