apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: AWSMachineTemplate
metadata:
  name: "{{ .Values.cluster.name }}-control-plane"
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType:  {{ .Values.cluster.controlPlaneInstanceType }}
      sshKeyName:  {{ .Values.cluster.sshKeyName }}