apiVersion: cluster.x-k8s.io/v1alpha3
kind: MachineDeployment
metadata:
  name: "{{ .Values.cluster.name }}-worker"
  namespace: us-west-2
spec:
  clusterName: {{ .Values.cluster.name }}
  replicas: {{ .Values.cluster.workerReplicas }} 
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha3
          kind: KubeadmConfigTemplate
          name: "{{ .Values.cluster.name }}-worker"
      clusterName: {{ .Values.cluster.name }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: AWSMachineTemplate
        name: "{{ .Values.cluster.name }}-worker"
      version: {{ .Values.cluster.kubernetesVersion }}